
[tool.ruff]
target-version = "py39"
line-length = 88

[tool.ruff.lint]
ignore = [
    # may be undefined, or defined from star imports
    "F405",
    # Module level import not at top of file
    "E402",
    # used; unable to detect undefined names
    "F403",
]

unfixable = [
  # Don't touch unused imports
  "F401",
]

[tool.ruff.lint.isort]
known-first-party = ["syntax_highlighting_ng"]

[tool.ruff.lint.flake8-quotes]
inline-quotes = "double"

[tool.ruff.lint.flake8-tidy-imports]
ban-relative-imports = "all"

[tool.ruff.lint.per-file-ignores]
# Tests can use relative imports and assertions
"tests/**/*" = ["TID252", "S101"]


[[tool.mypy.overrides]]
module = [
    "pygments.*",
    "aqt.*",
    "anki.*",
]
ignore_missing_imports = true
