# -*- coding: utf-8 -*-

"""
Anki Add-on: Syntax Highlighting

Module-level entry point for the add-on into Anki 2.0.x/2.1.x

Please do not edit this file if you are not sure what you are doing.

Copyright: (c) 2018 Glutanimate <https://glutanimate.com/>
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl.html>
"""
import os

from ._version import __version__  # noqa: F401

# we need to import syntax_highlighting_ng without an installed anki,
# hence this workaround
# an improved design would be shifting all the addon api ia separate module
# (eg. addon.py) and leaving __init__.py almost empty

STANDALONE = False
try:
    from . import main  # noqa: F401
except ModuleNotFoundError:
    if not os.environ.get("STANDALONE_ADDON") == "1":
        raise
    STANDALONE = True
